### ISSUE TITLE
Low effective sample size in m12.6.jl

### ISSUE THREAD

**Issue by fisherc2** [StanJulia/StatisticalRethinking.jl#1]
Hi -

The Turing model in m12.6.jl appears to have a low effective sample size.  m12.1.jl and m12.2.jl seem to be good, but I have not tested the others because their run times are long.  It's not clear why all the models have long run times. From  what I gathered, there might be ongoing performance issues with Turing that have not been fully resolved (see https://github.com/TuringLang/Turing.jl/issues/325).  So the run time issue may not be related to the model specification of the examples. 

**m12.6.jl**
```
using StatisticalRethinking
using Turing

Turing.setadbackend(:reverse_diff)

d = CSV.read(joinpath(dirname(Base.pathof(StatisticalRethinking)), "..", "data",
    "Kline.csv"), delim=';');
size(d) # Should be 10x5

d[:log_pop] = map((x) -> log(x), d[:population]);
d[:society] = 1:10;

@model m12_6(total_tools, log_pop, society) = begin

    N = length(total_tools)

    α ~ Normal(0, 10)
    βp ~ Normal(0, 1)

    σ_society ~ Truncated(Cauchy(0, 1), 0, Inf)

    N_society = length(unique(society)) #10

    α_society = Vector{Real}(undef, N_society)

    α_society ~ [Normal(0, σ_society)]

    for i ∈ 1:N
        λ = exp(α + α_society[society[i]] + βp*log_pop[i])
        total_tools[i] ~ Poisson(λ)
    end
end

posterior = sample(m12_6(d[:total_tools], d[:log_pop],
    d[:society]), Turing.NUTS(4000, 1000, 0.95));

describe(posterior)

```
**Results**
```
[NUTS] Sampling...100% Time: 0:03:10
[NUTS] Finished with
  Running time        = 189.01329048200012;
  #lf / sample        = 0.0035;
  #evals / sample     = 186.61175;
  pre-cond. metric    = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0,....
Iterations = 1:4000
Thinning interval = 1
Chains = 1
Samples per chain = 4000

Empirical Posterior Estimates:
                   Mean             SD           Naive SE           MCSE          ESS
            α    0.770457654    0.8398108547   0.013278575523   0.09904739668   71.891383
 α_society[9]    0.337460060    0.4270482149   0.006752225149   0.06140214467   48.371187
       lf_num    0.003500000    0.2213594362   0.003500000000   0.00350000000 4000.000000
 α_society[8]   -0.140869387    0.2497780406   0.003949337588   0.02613925834   91.310766
      elapsed    0.047253323    0.0828856831   0.001310537721   0.00092100913 4000.000000
      epsilon    0.005160425    0.0016025041   0.000025337815   0.00005154582  966.521282
 α_society[3]    0.021898862    0.2591870665   0.004098107351   0.02527437584  105.163680
 α_society[1]   -0.096965256    0.4072306578   0.006438882059   0.05316658157   58.668294
α_society[10]   -0.171333714    0.3778259984   0.005973953571   0.04304737075   77.035413
 α_society[5]    0.076119591    0.2271698255   0.003591870321   0.01887655095  144.829156
     eval_num  186.611750000   23.2244882861   0.367211402380   2.91686468678   63.395691
 α_society[7]    0.221995564    0.3807670154   0.006020455133   0.05339425422   50.854524
    σ_society    0.413636355    0.4968162365   0.007855354429   0.07478289106   44.135399
 α_society[2]    0.139162211    0.2897333942   0.004581087200   0.03116427768   86.433675
 α_society[6]   -0.279303630    0.2994251039   0.004734326584   0.03499527610   73.207836
           βp    0.042494276    2.2630663543   0.035782220879   0.25111254635   81.219021
           lp -865.815326541 7545.5204017129 119.305153003407 826.42652778225   83.362340
 α_society[4]    0.423954360    0.3775198792   0.005969113402   0.05089604479   55.018859
       lf_eps    0.005160425    0.0016025041   0.000025337815   0.00005154582  966.521282
```

**Comment by fisherc2** [comment]
I forgot to mention my system and software specs:

```
versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  JULIA_CMDSTAN_HOME = /home/dfish/cmdstan-2.17.1
  JULIA_EDITOR = atom -a
  JULIA_NUM_THREADS = 4
```

```
[fce5fe82] Turing v0.6.4
[2d09df54] StatisticalRethinking v0.4.0
```

**Comment by torkar** [comment]
You're forgetting the most likely reason, i.e., me messing things up when I translated the models ;)

**Comment by torkar** [comment]
If you find something strange then a pull request is most welcome! :)

**Comment by fisherc2** [comment]
Will do.

I'm not very familiar with Poisson regression, but your code appears to be equivalent to the Stan model found [here](https://github.com/ssp3nc3r/rethinking/blob/master/chapter12.Rmd). So it's not clear to me why the effective sample size is so low.

**Comment by goedman** [comment]
Chris,

 I think the results should be something like:

```
Iterations = 1:1000
Thinning interval = 1
Chains = 1,2,3,4
Samples per chain = 1000

Empirical Posterior Estimates:
                   Mean            SD         Naive SE         MCSE         ESS    
         lp__  928.043391500  2.9801830251 0.047120831017 0.10412981885  819.097589
accept_stat__    0.936485280  0.0890638723 0.001408223469 0.00168386155 1000.000000
   stepsize__    0.054044275  0.0023661368 0.000037411907 0.00037883775   39.009752
  treedepth__    5.814750000  0.4684947271 0.007407552047 0.01877323347  622.775117
 n_leapfrog__   68.612000000 29.6538242614 0.468868130001 0.85627002690 1000.000000
  divergent__    0.000000000  0.0000000000 0.000000000000 0.00000000000         NaN
     energy__ -921.505192750  3.9165026073 0.061925343505 0.12391326621  998.990207
            a    1.101570431  0.7094342566 0.011217140506 0.02253883312  990.744009
           bp    0.260531749  0.0765491451 0.001210348257 0.00239107665 1000.000000
  a_society.1   -0.197773466  0.2306720863 0.003647245927 0.00536358286 1000.000000
  a_society.2    0.044530077  0.2139312867 0.003382550643 0.00518870890 1000.000000
  a_society.3   -0.041954795  0.1845972632 0.002918739008 0.00433489806 1000.000000
  a_society.4    0.326263470  0.1895911420 0.002997699165 0.00557424414 1000.000000
  a_society.5    0.046117209  0.1762603065 0.002786920147 0.00413155547 1000.000000
  a_society.6   -0.310893727  0.2033643874 0.003215473297 0.00550744282 1000.000000
  a_society.7    0.146506828  0.1701311145 0.002690009113 0.00373704400 1000.000000
  a_society.8   -0.164561717  0.1799417945 0.002845129585 0.00416658848 1000.000000
  a_society.9    0.276327443  0.1738077910 0.002748142474 0.00486988593 1000.000000
 a_society.10   -0.089019497  0.2748128829 0.004345173202 0.00812819300 1000.000000
sigma_society    0.304580809  0.1224826068 0.001936620057 0.00369141520 1000.000000
```

I've added 2 versions of Stan models, the [one you posted above](https://github.com/StanJulia/StatisticalRethinking.jl/blob/master/scripts/12/m12.6.2s.jl) and the version generated by [McElreath's ulam()](https://github.com/StanJulia/StatisticalRethinking.jl/blob/master/scripts/12/m12.6.1s.jl).

I think Richard is also short changing himself, his models are fine. In general, it might be possible to optimize the Turing performance for these models as has been demonstrated in the original publication on Turing (and in some other examples I've seen). In your case, where you often need to generate the likelihood, that's where you might have opportunities I think.

In your case above, I think there is still an issue with describe() and NUTS() sampling.

**Comment by fisherc2** [comment]
Hi Rob-

Can you refer me to the example or publication you are referring to? I would like to see if I can figure out an optimization. You also mentioned there might be something wrong with describe() and NUTS(). Do you mean a bug or problem in Turing, or do you mean that the NUTS parameters are poorly selected? Thanks.

**Comment by goedman** [comment]
Hi Chris, does this [link](https://dblp.org/rec/bib2/conf/aistats/GeXG18.bib) work? Or http://turing.ml ?

Yes, NUTS samples in Turing in the MCMCChain include the adaptation samples. In the above Turing run only the final 3000 samples should be used.

**Comment by fisherc2** [comment]
Thanks, Rob. Those links work. I'll see if I can make sense out of the papers.

Ok. Thanks for clarifying that adapt is the same as warmup or burnin. I thought it referred to something else. Other packages such as Stan and Mamba automatically exclude the burnin samples from the chain, but I did not find any info about how to do this. Are you aware of  an elegant way to remove the burning samples from the chain? Thanks

**Comment by goedman** [comment]
I use something like `chn2 = MCMCChain.Chains(chn.value[1001:4000, :,: ], names=chn.names)` for 1000 adaptation samples.

**Comment by fisherc2** [comment]
Ok. That makes sense. I suppose your Stan code does something similar in the background and returns the chain without the burnin samples as you described.

**Comment by fisherc2** [comment]
Hi Rob-

I have a question about the computation of effective sample size, particularly when multiple chains are used. As far as I can tell based on the code [here](https://github.com/TuringLang/MCMCChain.jl/blob/master/src/stats.jl) (line 118), effective sample size appears to be equal to the number of samples in a single chain. I'm not familiar with the details of effective sample size, but this strikes me as odd. It seems to me that it could overestimate the effective sample size when autocorrelation is high and underestimate effective sample size when samples within each chain are mostly independent. I'm pretty sure this is different than Stan's native calculations. Am I misunderstanding something?

**Comment by goedman** [comment]
I’ll have to refresh my memory but seem to recall multiple chains are important for the correlation needed to compute the ESS. I’ll have a look. Have you considered WAIC and friends? Another area I need to dig deeper into!

**Comment by goedman** [comment]
Chris, looking at a slightly more complicated model I see below results. These estimates of ESS seem pretty reasonable/comparable. Note also Richard Torkar's note in m8.1 in SR:

```
# Here we will use Turing's NUTS support, which is currently (2018) the originalNUTS by [Hoffman & Gelman]( http://www.stat.columbia.edu/~gelman/research/published/nuts.pdf) and not the one that's in Stan 2.18.2, i.e., Appendix A.5 in: https://arxiv.org/abs/1701.02434
```
The line 118 you mention above retrieves the ESS values from Turing.

Turing m8.1 in SR ( I have updated m8.1 to do 500 warmups, 500 samples, as in R's rethinking):
```
julia> describe(posterior2)
Iterations = 1:500
Thinning interval = 1
Chains = 1
Samples per chain = 500

Empirical Posterior Estimates:
              Mean                   SD                       Naive SE              MCSE        ESS   
       α    9.236001727  0.139979858032590220862090 0.0062600895608328340977144 0.0072621843 371.53229
  lf_num    0.000000000  0.000000000000000000000000 0.0000000000000000000000000 0.0000000000       NaN
      βA   -1.959147343  0.227559963323169772708710 0.0101767909389593319557932 0.0150545723 228.48351
      βR   -0.207507225  0.076837852113119081698400 0.0034362932114002028849420 0.0045783692 281.66236
       σ    0.948133574  0.056199375996908093600091 0.0025133125004431302630670 0.0014341875 500.00000
 elapsed    0.118077238  0.064602519801849694891516 0.0028891125158942432271658 0.0031892969 410.30708
 epsilon    0.027768298  0.000000000000000013891686 0.0000000000000000006212551 0.0000000000 500.00000
eval_num   45.760000000 24.580944768079657336556920 1.0992932690518784077937653 1.0886321693 500.00000
     βAR    0.401405080  0.123608980277352148435810 0.0055279616505918040270107 0.0063330853 380.95123
      lp -248.501695452  1.606431364589359755967735 0.0718417946481911401379605 0.1464664013 120.29521
  lf_eps    0.027768298  0.000000000000000013891686 0.0000000000000000006212551 0.0000000000 500.00000
```

For Stan I see:
```
precis(m8.1stan)
       mean   sd  5.5% 94.5% n_eff Rhat
a      9.22 0.13  9.01  9.44   272 1.01
bR    -0.20 0.08 -0.32 -0.08   287 1.01
bA    -1.94 0.22 -2.28 -1.60   270 1.01
bAR    0.39 0.13  0.18  0.58   283 1.00
sigma  0.95 0.05  0.87  1.03   458 1.00
```

The equivalent Stan model (generated in ulam()):
```
> stancode(m8.1stan)
data{
    real log_gdp[170];
    int cont_africa[170];
    real rugged[170];
}
parameters{
    real a;
    real bR;
    real bA;
    real bAR;
    real sigma;
}
model{
    vector[170] mu;
    sigma ~ cauchy( 0 , 2 );
    bAR ~ normal( 0 , 10 );
    bA ~ normal( 0 , 10 );
    bR ~ normal( 0 , 10 );
    a ~ normal( 0 , 100 );
    for ( i in 1:170 ) {
        mu[i] = a + bR * rugged[i] + bA * cont_africa[i] + bAR * rugged[i] * cont_africa[i];
    }
    log_gdp ~ normal( mu , sigma );
}

**Comment by fisherc2** [comment]
Hi Rob- 

Thanks for the information. I just want to clarify something about ESS since its a bit out of my domain. Do you think it is computing ESS correctly for multiple chains or do you think its provisional or a placeholder? 

Based on your post above, it looks like Turing and Stan are comparable  for m8.1. However, do you think that m12.6 is still problematic? It seems low to me (ESS ≈ 100 out of 4000 samples). I cannot use Stan as a reference point because of some issues with StatisticalRethinking.jl. I will post a separate issue for that.

**Comment by fisherc2** [comment]
I noticed that the standard deviations are much larger for the Turing model. Here is a comparison for the group level parameters for illustration:

```
bp:                        .078  vs.  .176
a:                         .732  vs.  1.20
sigma_society:    .129  vs  .357
```

Something still appears to be wrong, but the cause still alludes me.

**Comment by fisherc2** [comment]
I also wanted to look at the gelman rhat statistics. I ran the Turing version with acceptance rate of .95, four chains, 4000 samples each,  with 1000 adaption samples removed. 

```
Iterations = 1:2000
Thinning interval = 1
Chains = 1,2,3,4
Samples per chain = 2000

                    PSRF           97.5%    
            α   1.0570000×10⁰  1.1500000×10⁰
 α_society[9]   1.0050000×10⁰  1.0120000×10⁰
       lf_num             NaN            NaN
 α_society[8]   1.0020000×10⁰  1.0040000×10⁰
      elapsed   1.0140000×10⁰  1.0420000×10⁰
      epsilon 2.13076927×10¹⁴ 4.3694579×10¹⁴
 α_society[3]   1.0110000×10⁰  1.0320000×10⁰
 α_society[1]   1.0280000×10⁰  1.0800000×10⁰
α_society[10]   1.0230000×10⁰  1.0620000×10⁰
 α_society[5]   1.0050000×10⁰  1.0150000×10⁰
     eval_num   1.1520000×10⁰  1.1540000×10⁰
 α_society[7]   1.0060000×10⁰  1.0170000×10⁰
    σ_society   1.0070000×10⁰  1.0150000×10⁰
 α_society[2]   1.0210000×10⁰  1.0590000×10⁰
 α_society[6]   1.0020000×10⁰  1.0050000×10⁰
           βp   1.0530000×10⁰  1.1380000×10⁰
           lp   1.0040000×10⁰  1.0110000×10⁰
 α_society[4]   1.0070000×10⁰  1.0180000×10⁰
       lf_eps 2.13076927×10¹⁴ 4.3694579×10¹⁴

```
Convergence for some parameters looks good, while others like βp and  α are somewhat large.

**Comment by fisherc2** [comment]
By the way, if the speed problem persists after we figure out the ESS issue, I was thinking about opening an issue on Turing. Currently, with four chains, 4000 samples, 1000 burnin samples, and target acceptance rate of .95, Turing requires 196 seconds whereas Stan only requires 2.18 seconds, a gap of nearly 2 orders of magnitude. Supposedly, Julia is capable of being within a factor of 2 of C. It makes me wonder whether there are still optimizations to be made in Turing or whether Julia does not perform well outside of micro-benchmarks.

**Comment by goedman** [comment]
Naively I have always assumed part of the extra time needed by Turing might be AD related. In another thread I did see a post by Tamas Papp where he mentioned that for large models he still codes derivatives manually. And Richard's remark on differences between Turing's NUTS and what's in stan currently.

**Comment by fisherc2** [comment]
Thanks for the info. I'll see if I can track down those posts. I was under the impression that Stan uses AD. Perhaps its better optimized or it uses explicit derivative information for typical models.

**Comment by fisherc2** [comment]
I came across this[ pull request](https://github.com/TuringLang/Turing.jl/pull/641) for Turing where a model from this package was producing low ESS. I'm not sure if its related to the problem described here.

**Comment by goedman** [comment]
Hi Chris, interesting, I think we should bring the low ESS values for m12.6 up on Turing together with above link. This is not something we (I at least) can add a lot of value.

**Comment by fisherc2** [comment]
Sounds good. I'll go ahead and make a reference to this issue on the Turing issue. Thanks!

**Comment by fisherc2** [comment]
Rob, I will close this issue since its most likely due to the adaption bug in Turing.

**Comment by goedman** [comment]
Thanks Chris, not was also getting pretty long (but useful for me).
